title = "Charles Murry"
baseURL = "https://charliemurry.github.io"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Charles Murry"
  description = "Economist at Boston College"
  favicon = "icon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "By Charles Murry"
    url = "https://github.com/charliemurry"
  [params.style]  # appearance options (can be omitted)
    headingFontFamily = "Open Sans"
    fontFamily = "Open Sans"
    fontSize = "15pt"
    pageWidth = "850px"
    lineHeight = "1.6"
    avatarSize = "220px"    
    colorBlack = "#222222"
    colorRed = "#222840"   # This controls links
    colorAccent = "#2962ff"  # A professional blue for links
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/charliemurry"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:charles.murry@bc.edu"
  [[params.socialIcons]]
    icon = "ai ai-google-scholar"
    title = "Scholar"
    url = "https://scholar.google.com/citations?user=RdTkmEUAAAAJ&hl=en"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "About"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    # pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    # post = '<svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/></svg>'
    weight = 3
  [[menu.main]]
    name = "CV"
    url = "/cv"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
theme = 'researcher'
